--- ###Trial and still error### :)))))
- name: Install Plesk
  hosts: Plesk
  remote_user: root

  tasks:
  - name: Ensure SELinux is set to enforcing mode
    ansible.builtin.lineinfile:
     path: /etc/selinux/config
     regexp: '^SELINUX='
     line: SELINUX=disabled
     
  - name: Upgrade all packages
    yum:
     name: '*'
     state: latest
     
  - name: Stop service Network Manager on Centos, if running
    ansible.builtin.systemd:
     name: NetworkManager
     enabled: no
     state: stopped
     
  - name: download Plesk to home dir
    shell: curl https://autoinstall.plesk.com/one-click-installer || wget -O - https://autoinstall.plesk.com/one-click-installer
     
  - name: Start service Network Manager
    ansible.builtin.systemd:
     name: NetworkManager
     enabled: yes
     state: started
